name: Cypress Regression Tests

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  cypress-regression:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install

    - name: Run Cypress regression tests
      run: npm run cy:regression

    - name: Upload report artifact
      uses: actions/upload-artifact@v4
      with:
        name: mochawesome-report
        path: cypress/reports/html/index.html
        retention-days: 30
        if-no-files-found: warn

    - name: Send notification to Slack
      if: failure()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.PIPELINESLACKCONECTION }}
      run: |
        payload="payload={\"text\":\":x: Pipeline '${{ github.workflow }}' failed on branch '${{ github.ref }}' in repository '${{ github.repository }}'\"}"
        curl -X POST --data-urlencode "$payload" $SLACK_WEBHOOK_URL

    env:
      CI: true